package com.activenture.mib.entity;
// Generated Oct 6, 2018 3:15:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name = "posts", catalog = "activent_mib_dev")
public class Posts implements java.io.Serializable {

	private Long postId;
	private Date dtCreate;
	private Date dtModify;
	private String postTitle;
	private String postBody;
	private Integer isActive;

	public Posts() {
	}

	public Posts(Date dtCreate, Date dtModify) {
		this.dtCreate = dtCreate;
		this.dtModify = dtModify;
	}

	public Posts(Date dtCreate, Date dtModify, String postTitle, String postBody, Integer isActive) {
		this.dtCreate = dtCreate;
		this.dtModify = dtModify;
		this.postTitle = postTitle;
		this.postBody = postBody;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "post_id", unique = true, nullable = false)
	public Long getPostId() {
		return this.postId;
	}

	public void setPostId(Long postId) {
		this.postId = postId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_create", nullable = false, length = 19)
	public Date getDtCreate() {
		return this.dtCreate;
	}

	public void setDtCreate(Date dtCreate) {
		this.dtCreate = dtCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_modify", nullable = false, length = 19)
	public Date getDtModify() {
		return this.dtModify;
	}

	public void setDtModify(Date dtModify) {
		this.dtModify = dtModify;
	}

	@Column(name = "post_title")
	public String getPostTitle() {
		return this.postTitle;
	}

	public void setPostTitle(String postTitle) {
		this.postTitle = postTitle;
	}

	@Column(name = "post_body")
	public String getPostBody() {
		return this.postBody;
	}

	public void setPostBody(String postBody) {
		this.postBody = postBody;
	}

	@Column(name = "is_active")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

}
