package com.activenture.mib.entity;
// Generated Nov 23, 2018 12:00:43 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuickApply generated by hbm2java
 */
@Entity
@Table(name = "quick_apply", catalog = "activent_mib_dev")
public class QuickApply implements java.io.Serializable {

	private long enquiryId;
	private Date dtCreate;
	private Date dtUpdate;
	private String categoryId;
	private String name;
	private String email;
	private String mobile;
	private String applicantStatus;
	private String employmentStatus;
	private String country;
	private String city;
	private String amount;
	private String subCategory;
	private String comment;
	private String attachFileServer;
	private String attachFileUser;
	private long isActive=1;

	public QuickApply() {
	}

	public QuickApply(Date dtCreate, Date dtUpdate) {
		this.dtCreate = dtCreate;
		this.dtUpdate = dtUpdate;
	}

	public QuickApply(Date dtCreate, Date dtUpdate, String categoryId, String name, String email, String mobile,
			String applicantStatus, String employmentStatus, String country, String city, String amount,
			String subCategory, String comment, String attachFileServer, String attachFileUser, long isActive) {
		this.dtCreate = dtCreate;
		this.dtUpdate = dtUpdate;
		this.categoryId = categoryId;
		this.name = name;
		this.email = email;
		this.mobile = mobile;
		this.applicantStatus = applicantStatus;
		this.employmentStatus = employmentStatus;
		this.country = country;
		this.city = city;
		this.amount = amount;
		this.subCategory = subCategory;
		this.comment = comment;
		this.attachFileServer = attachFileServer;
		this.attachFileUser = attachFileUser;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "enquiry_id", unique = true, nullable = false)
	public long getEnquiryId() {
		return this.enquiryId;
	}

	public void setEnquiryId(long enquiryId) {
		this.enquiryId = enquiryId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_CREATE", nullable = false, length = 19)
	public Date getDtCreate() {
		return this.dtCreate;
	}

	public void setDtCreate(Date dtCreate) {
		this.dtCreate = dtCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_UPDATE", nullable = false, length = 19)
	public Date getDtUpdate() {
		return this.dtUpdate;
	}

	public void setDtUpdate(Date dtUpdate) {
		this.dtUpdate = dtUpdate;
	}

	@Column(name = "CATEGORY_ID", length = 100)
	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MOBILE")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "APPLICANT_STATUS")
	public String getApplicantStatus() {
		return this.applicantStatus;
	}

	public void setApplicantStatus(String applicantStatus) {
		this.applicantStatus = applicantStatus;
	}

	@Column(name = "EMPLOYMENT_STATUS")
	public String getEmploymentStatus() {
		return this.employmentStatus;
	}

	public void setEmploymentStatus(String employmentStatus) {
		this.employmentStatus = employmentStatus;
	}

	@Column(name = "COUNTRY")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "CITY")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "AMOUNT")
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Column(name = "SUB_CATEGORY")
	public String getSubCategory() {
		return this.subCategory;
	}

	public void setSubCategory(String subCategory) {
		this.subCategory = subCategory;
	}

	@Column(name = "COMMENT")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "ATTACH_FILE_SERVER")
	public String getAttachFileServer() {
		return this.attachFileServer;
	}

	public void setAttachFileServer(String attachFileServer) {
		this.attachFileServer = attachFileServer;
	}

	@Column(name = "ATTACH_FILE_USER")
	public String getAttachFileUser() {
		return this.attachFileUser;
	}

	public void setAttachFileUser(String attachFileUser) {
		this.attachFileUser = attachFileUser;
	}

	@Column(name = "IS_ACTIVE")
	public long getIsActive() {
		return this.isActive;
	}

	public void setIsActive(long isActive) {
		this.isActive = isActive;
	}

}
