package com.activenture.mib.entity;
// Generated Oct 18, 2018 12:50:28 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubscribedUser generated by hbm2java
 */
@Entity
@Table(name = "subscribed_user", catalog = "activent_mib_dev")
public class SubscribedUser implements java.io.Serializable {

	private long subscribeId;
	private Date dtCreate;
	private Date dtModify;
	private String userEmail;
	private int isActive=1;

	public SubscribedUser() {
	}

	public SubscribedUser(Date dtCreate, Date dtModify, int isActive) {
		this.dtCreate = dtCreate;
		this.dtModify = dtModify;
		this.isActive = isActive;
	}

	public SubscribedUser(Date dtCreate, Date dtModify, String userEmail, int isActive) {
		this.dtCreate = dtCreate;
		this.dtModify = dtModify;
		this.userEmail = userEmail;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "subscribe_id", unique = true, nullable = false)
	public long getSubscribeId() {
		return this.subscribeId;
	}

	public void setSubscribeId(long subscribeId) {
		this.subscribeId = subscribeId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_create", nullable = false, length = 19)
	public Date getDtCreate() {
		return this.dtCreate;
	}

	public void setDtCreate(Date dtCreate) {
		this.dtCreate = dtCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_modify", nullable = false, length = 19)
	public Date getDtModify() {
		return this.dtModify;
	}

	public void setDtModify(Date dtModify) {
		this.dtModify = dtModify;
	}

	@Column(name = "user_email")
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "is_active", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

}
